prog:Personne.o main.o
	gcc Personne.o main.o -o prog -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
main.o:main.c
	gcc -c main.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
Personne.o:Personne.c
	gcc -c Personne.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf

